version: '3.8'

services:
  reconxploit:
    build: .
    image: kernelpanic/reconxploit:3.0.0
    container_name: reconxploit

    environment:
      - RECONXPLOIT_HOME=/opt/reconxploit
      - PYTHONPATH=/opt/reconxploit

    volumes:
      - ./results:/opt/reconxploit/results
      - ./logs:/opt/reconxploit/logs
      - ./config:/opt/reconxploit/config
      - ./wordlists:/opt/reconxploit/wordlists

    network_mode: host

    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G

    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    user: "1000:1000"

    working_dir: /opt/reconxploit

    command: ["--help"]

networks:
  default:
    driver: bridge

volumes:
  reconxploit_data:
    driver: local
