# ReconXploit v3.0 - Main Configuration
# Product of Kernelpanic under infosbios.tech

framework:
  version: "3.0.0"
  name: "ReconXploit"
  author: "cyb3r-ssrf"
  organization: "Kernelpanic" 
  website: "infosbios.tech"

# Performance and resource settings
performance:
  threads: 50
  timeout: 30
  delay: 0
  max_retries: 3
  rate_limit: 100
  memory_limit: "2GB"

# Output configuration
output:
  format: "html"  # html, json, csv, pdf, xml
  directory: "results"
  save_raw: true
  generate_summary: true
  include_screenshots: false
  timestamp_format: "%Y%m%d_%H%M%S"

# Tool configurations by category
tools:
  subdomain_enumeration:
    enabled: true
    tools: ["subfinder", "assetfinder"]
    timeout: 300
    max_results: 10000
    use_passive_sources: true
    use_certificate_transparency: true
    wordlists:
      - "wordlists/subdomains/subdomains-top1million-5000.txt"

  live_host_detection:
    enabled: true
    tools: ["httpx"]
    timeout: 30
    threads: 100
    follow_redirects: true
    verify_ssl: false
    check_response_codes: [200, 301, 302, 403, 404, 500]
    custom_headers: {}

  port_scanning:
    enabled: true
    tools: ["naabu", "nmap"]
    timeout: 600
    top_ports: 1000
    scan_type: "syn"
    exclude_ports: []
    rate_limit: 1000
    custom_ports: []

  content_discovery:
    enabled: true
    tools: ["feroxbuster", "gobuster"]
    timeout: 900
    wordlists:
      - "wordlists/directories/common.txt"
      - "wordlists/directories/big.txt"
    extensions: ["php", "html", "js", "css", "txt", "json", "xml"]
    recursion_depth: 3
    follow_redirects: true
    status_codes: [200, 301, 302, 403]

  parameter_discovery:
    enabled: true
    tools: ["arjun", "paramspider"]
    timeout: 300
    methods: ["GET", "POST"]
    wordlists:
      - "wordlists/parameters/common-parameters.txt"
    check_reflection: true

  vulnerability_scanning:
    enabled: true
    tools: ["nuclei"]
    timeout: 1800
    templates: "all"
    severity: ["critical", "high", "medium", "low"]
    exclude_tags: ["dos", "intrusive"]
    update_templates: true
    custom_templates: []

# Network and proxy settings
network:
  user_agent: "ReconXploit/3.0 (+https://infosbios.tech)"
  timeout: 30
  max_redirects: 5
  verify_ssl: false
  proxy:
    enabled: false
    http: ""
    https: ""
    socks: ""
  dns:
    servers: ["8.8.8.8", "1.1.1.1", "9.9.9.9"]
    timeout: 5

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "logs/reconxploit.log"
  max_size: "100MB"
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  console: true

# Notification settings (optional)
notifications:
  enabled: false
  webhook_url: ""
  slack:
    enabled: false
    token: ""
    channel: "#reconxploit"
  discord:
    enabled: false
    webhook_url: ""
  email:
    enabled: false
    smtp_server: ""
    port: 587
    username: ""
    password: ""
    from_addr: ""
    to_addr: ""

# Rate limiting and safety
rate_limits:
  default: 100  # requests per minute
  shodan: 1
  censys: 5
  virustotal: 4
  github: 60

# Wordlists configuration
wordlists:
  base_directory: "wordlists"
  auto_update: false
  sources:
    - "https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/DNS/subdomains-top1million-5000.txt"
    - "https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/Web-Content/common.txt"

# Database settings (if using database storage)
database:
  enabled: false
  type: "sqlite"  # sqlite, postgresql, mysql
  host: "localhost"
  port: 5432
  name: "reconxploit"
  username: ""
  password: ""

# Advanced settings
advanced:
  max_concurrent_scans: 5
  cleanup_temp_files: true
  debug_mode: false
  experimental_features: false
