# ReconXploit v3.0 - Main Configuration File
# Product of Kernelpanic under infosbios.tech

framework:
  version: "3.0.0"
  name: "ReconXploit"
  author: "cyb3r-ssrf"
  organization: "Kernelpanic"
  website: "infosbios.tech"

defaults:
  threads: 50
  timeout: 30
  user_agent: "ReconXploit/3.0 (Kernelpanic; +https://infosbios.tech)"
  output_format: "html"
  output_directory: "results"

tools:
  subdomain_enumeration:
    enabled: true
    tools: ["subfinder", "amass", "assetfinder", "sublist3r", "findomain"]
    timeout: 300

  port_scanning:
    enabled: true
    tools: ["naabu", "masscan", "nmap"]
    top_ports: 1000

  web_crawling:
    enabled: true
    tools: ["katana", "hakrawler", "gospider", "gau", "waybackurls"]
    depth: 3

  content_discovery:
    enabled: true
    tools: ["ffuf", "dirsearch", "gobuster", "feroxbuster"]
    wordlist: "wordlists/SecLists/Discovery/Web-Content/common.txt"

  vulnerability_scanning:
    enabled: true
    tools: ["nuclei", "nikto"]
    nuclei_templates: "all"

rate_limits:
  default: 100
  shodan: 1
  censys: 5
  securitytrails: 10

output:
  save_raw: true
  generate_reports: true
  formats: ["json", "csv", "html"]

notifications:
  enabled: false
  webhook_on_completion: true
  email_on_error: false
